The PCR cli tool is a tool used to help us manage the packages.

Building the tool

To create pcr binaries as per the OS, please follow below commands.

build in Windows :

	go build -o pcr.exe .

build in Linux :
     go build -o pcr .	


Setting Path Variables

Once you create the pcr binaries, add it to the Enviromental variables. To do so:-

For Windows :

- Open the Start Search, type in “env”, and choose “Edit the system environment variables”
- Click the “Environment Variables…” button
- Under the “System Variables” section (the lower half), find the row with “Path” in the first column, and click edit
- The “Edit environment variable” UI will appear. Here, click “New” and type in the path of the pcr binaries.
- Click OK
- To check in new PowerShell window, type: $env:PATH

For Linux: 

- Open Terminal and type below command
- export PATH=$PATH:"path of pcr binary"







